# Generated by Django 2.0.2 on 2018-02-03 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_date', models.DateField(verbose_name='sleep date')),
                ('time_start_preparing_for_sleep', models.DateTimeField(verbose_name='time started getting ready for bed')),
                ('time_went_into_bed', models.DateTimeField(verbose_name='time in bed')),
                ('time_went_to_sleep', models.DateTimeField(verbose_name='time asleep')),
                ('time_woke_in_morning', models.DateTimeField(verbose_name='time woke in morning')),
            ],
        ),
        migrations.CreateModel(
            name='SleepInterruption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interruption_time', models.TimeField(verbose_name='time woke during sleep')),
                ('intervention', models.CharField(max_length=200)),
                ('time_taken_to_sleep', models.IntegerField(default=10)),
                ('sleep_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sleep.Sleep')),
            ],
        ),
    ]
