# Generated by Django 2.0.2 on 2018-02-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='time_start_preparing_for_sleep',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time started getting ready for bed'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='time_went_into_bed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time in bed'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='time_went_to_sleep',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time asleep'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='time_woke_in_morning',
            field=models.DateTimeField(blank=True, verbose_name='time woke in morning'),
        ),
    ]
