# Generated by Django 2.0.2 on 2018-02-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0002_auto_20180203_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='time_woke_in_morning',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time woke in morning'),
        ),
    ]
