# Generated by Django 2.0.2 on 2018-02-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0004_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
